version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "01:00"
  ignore:
    - dependency-name: coverage
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "01:00"