version: "3"
services:
  app:
    image: luisalejandro/agoras:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/agoras/app
      - ~/Library/Caches/pip:/home/agoras/.cache/pip
    env_file:
      - .env
