version: "3"
services:
  agoras:
    image: luisalejandro/agoras:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/luisalejandro/app
      - /home/luisalejandro/.pypirc:/home/luisalejandro/.pypirc
