name: Functional tests

on:
  workflow_dispatch:
  schedule:
    - cron: "00 6 * * 2"

jobs:
  functional:
    name: Functional tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"

      - name: Installing dependencies
        run: |
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install -r requirements.txt

      - name: Configuring secrets
        run: |
          KEYS="TWITTER_STATUS_TEXT TWITTER_STATUS_IMAGE_URL_1 TWITTER_CONSUMER_KEY TWITTER_CONSUMER_SECRET TWITTER_OAUTH_TOKEN TWITTER_OAUTH_SECRET FACEBOOK_STATUS_TEXT FACEBOOK_STATUS_IMAGE_URL_1 FACEBOOK_ACCESS_TOKEN FACEBOOK_OBJECT_ID FACEBOOK_PROFILE_ID INSTAGRAM_ACCESS_TOKEN INSTAGRAM_OBJECT_ID INSTAGRAM_STATUS_TEXT INSTAGRAM_STATUS_IMAGE_URL_1 LINKEDIN_STATUS_TEXT LINKEDIN_STATUS_IMAGE_URL_1 LINKEDIN_ACCESS_TOKEN POST_LOOKBACK FEED_URL GOOGLE_SHEETS_CLIENT_EMAIL GOOGLE_SHEETS_PRIVATE_KEY GOOGLE_SHEETS_ID GOOGLE_SHEETS_NAME"
          { for key in $KEYS; do echo "$key"; done } | { while read key; do echo "$key=$(echo $SECRETS_CONTEXT | jq .$key)"; done } > secrets.env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Testing twitter
        run: bash test.sh twitter

      - name: Testing facebook
        run: bash test.sh facebook

      - name: Testing linkedin
        run: bash test.sh linkedin
