name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
    branches:
      - develop

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: "3.9"
            toxenv: "py39"
          - python-version: "3.10"
            toxenv: "py310"
          - python-version: "3.11"
            toxenv: "py311"
          - python-version: "3.12"
            toxenv: "py312"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install -r requirements.txt

      - name: Measuring coverage
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tox -e ${TOXENV}

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-py${{ matrix.python-version }}
          path-to-lcov: ./.lcov
          parallel: true

  finish:
    name: Finish
    runs-on: ubuntu-22.04
    needs: unit
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  approve:
    name: Approve pull request
    runs-on: ubuntu-22.04
    needs: finish
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v3.2.1
        with:
          github-token: "${{ github.actor == 'LuisAlejandro' && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"

  merge:
    name: Merge pull request
    runs-on: ubuntu-22.04
    needs: approve
    if: github.actor == github.repository_owner || github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@v6
        with:
          github-token: "${{ github.actor == github.repository_owner && secrets.GITHUB_TOKEN || secrets.REPO_PERSONAL_ACCESS_TOKEN }}"
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
