name: Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            toxenv: "py38"
            experimental: false
          - python-version: "3.9"
            toxenv: "py39"
            experimental: false
          - python-version: "3.10"
            toxenv: "py310"
            experimental: false
          - python-version: "3.11.0-beta.1"
            toxenv: "py311"
            experimental: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          sudo pip install -r requirements.txt -r requirements-dev.txt
      - name: Measuring coverage
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tox -e ${TOXENV}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-py${{ matrix.python-version }}
          path-to-lcov: ./.lcov
          parallel: true

  finish:
    name: Finish
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true